/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    guests: Guest;
    'vertical-carousel-media': VerticalCarouselMedia;
    'background-media': BackgroundMedia;
    'dress-code': DressCode;
    'gift-list': GiftList;
    rsvps: Rsvp;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    guests: GuestsSelect<false> | GuestsSelect<true>;
    'vertical-carousel-media': VerticalCarouselMediaSelect<false> | VerticalCarouselMediaSelect<true>;
    'background-media': BackgroundMediaSelect<false> | BackgroundMediaSelect<true>;
    'dress-code': DressCodeSelect<false> | DressCodeSelect<true>;
    'gift-list': GiftListSelect<false> | GiftListSelect<true>;
    rsvps: RsvpsSelect<false> | RsvpsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Repositório central de imagens e vídeos do site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Opcional para videos: cole o Link ou o src do iframe gerado no Video Player Studio do Cloudinary.
   */
  cloudinaryPlayerURL?: string | null;
  /**
   * Cloudinary Media Information
   */
  cloudinary?: {
    /**
     * Cloudinary Public ID (used for transformations)
     */
    public_id?: string | null;
    /**
     * Type of the resource (image, video, raw)
     */
    resource_type?: string | null;
    /**
     * File format
     */
    format?: string | null;
    /**
     * Secure delivery URL
     */
    secure_url?: string | null;
    /**
     * File size in bytes
     */
    bytes?: number | null;
    /**
     * Creation timestamp
     */
    created_at?: string | null;
    /**
     * Current version number
     */
    version?: string | null;
    /**
     * Unique version identifier
     */
    version_id?: string | null;
    /**
     * Width in pixels
     */
    width?: number | null;
    /**
     * Height in pixels
     */
    height?: number | null;
    /**
     * Duration in seconds (for videos)
     */
    duration?: number | null;
    /**
     * Number of pages (for PDFs)
     */
    pages?: number | null;
    /**
     * Which page of the PDF to use for thumbnails (changes will apply after saving)
     */
    selected_page?: number | null;
    /**
     * URL for the thumbnail image (automatically generated for PDFs)
     */
    thumbnail_url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Lista de convidados do casamento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests".
 */
export interface Guest {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  confirmed?: boolean | null;
  dependents?:
    | {
        name: string;
        age: number;
        type: 'spouse' | 'child' | 'other';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Imagens do carrossel vertical (galeria parallax / Skiper30).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vertical-carousel-media".
 */
export interface VerticalCarouselMedia {
  id: number;
  media: number | Media;
  order: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Imagens de fundo para seções do site (Hero, meio, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "background-media".
 */
export interface BackgroundMedia {
  id: number;
  media: number | Media;
  location: 'hero' | 'middle' | 'section1' | 'section2' | 'section3';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Conteúdo da seção de vestimenta (Dress Code).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dress-code".
 */
export interface DressCode {
  id: number;
  style: string;
  description: string;
  forHer: string;
  forHim: string;
  media: number | Media;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lista de presentes do casamento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-list".
 */
export interface GiftList {
  id: number;
  title: string;
  subtitle?: string | null;
  image: number | Media;
  price: number;
  /**
   * Se vazio, será usado o link padrão das configurações do site.
   */
  paymentLink?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestão de convites por família/grupo e envio de mensagens WhatsApp.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps".
 */
export interface Rsvp {
  id: number;
  groupName: string;
  phone: string;
  members?:
    | {
        name: string;
        status?: ('pending' | 'confirmed' | 'declined') | null;
        id?: string | null;
      }[]
    | null;
  token?: string | null;
  securityCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'guests';
        value: number | Guest;
      } | null)
    | ({
        relationTo: 'vertical-carousel-media';
        value: number | VerticalCarouselMedia;
      } | null)
    | ({
        relationTo: 'background-media';
        value: number | BackgroundMedia;
      } | null)
    | ({
        relationTo: 'dress-code';
        value: number | DressCode;
      } | null)
    | ({
        relationTo: 'gift-list';
        value: number | GiftList;
      } | null)
    | ({
        relationTo: 'rsvps';
        value: number | Rsvp;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryPlayerURL?: T;
  cloudinary?:
    | T
    | {
        public_id?: T;
        resource_type?: T;
        format?: T;
        secure_url?: T;
        bytes?: T;
        created_at?: T;
        version?: T;
        version_id?: T;
        width?: T;
        height?: T;
        duration?: T;
        pages?: T;
        selected_page?: T;
        thumbnail_url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests_select".
 */
export interface GuestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  confirmed?: T;
  dependents?:
    | T
    | {
        name?: T;
        age?: T;
        type?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vertical-carousel-media_select".
 */
export interface VerticalCarouselMediaSelect<T extends boolean = true> {
  media?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "background-media_select".
 */
export interface BackgroundMediaSelect<T extends boolean = true> {
  media?: T;
  location?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dress-code_select".
 */
export interface DressCodeSelect<T extends boolean = true> {
  style?: T;
  description?: T;
  forHer?: T;
  forHim?: T;
  media?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-list_select".
 */
export interface GiftListSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  image?: T;
  price?: T;
  paymentLink?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps_select".
 */
export interface RsvpsSelect<T extends boolean = true> {
  groupName?: T;
  phone?: T;
  members?:
    | T
    | {
        name?: T;
        status?: T;
        id?: T;
      };
  token?: T;
  securityCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configurações gerais do site em abas: casal, data, cores, fontes, pagamento e SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  couple: {
    coupleName: string;
    groomFullName: string;
    brideFullName: string;
  };
  weddingDate: string;
  countdownEnabled?: boolean | null;
  colors: {
    /**
     * Cor principal do site (ex: #ac5b30). Use o formato hexadecimal.
     */
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    textPrimaryColor: string;
    textSecondaryColor: string;
    backgroundColor: string;
  };
  fonts: {
    fontType: 'google' | 'custom';
    /**
     * Ex: Great Vibes, Cinzel, etc.
     */
    googleFontName?: string | null;
    /**
     * Upload de arquivo .woff2, .woff ou .ttf
     */
    customFontUpload?: (number | null) | Media;
  };
  payment?: {
    paymentMethodName?: string | null;
    /**
     * Usado quando o item da lista de presentes não tem link próprio.
     */
    defaultPaymentLink?: string | null;
    paymentInstructions?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  seo: {
    siteTitle: string;
    siteDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  couple?:
    | T
    | {
        coupleName?: T;
        groomFullName?: T;
        brideFullName?: T;
      };
  weddingDate?: T;
  countdownEnabled?: T;
  colors?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        textPrimaryColor?: T;
        textSecondaryColor?: T;
        backgroundColor?: T;
      };
  fonts?:
    | T
    | {
        fontType?: T;
        googleFontName?: T;
        customFontUpload?: T;
      };
  payment?:
    | T
    | {
        paymentMethodName?: T;
        defaultPaymentLink?: T;
        paymentInstructions?: T;
      };
  seo?:
    | T
    | {
        siteTitle?: T;
        siteDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}